### ISSUE TITLE
schedule.execute()

### ISSUE THREAD

**Issue by Shigawire** [HSOINES/Oekoflex#1]
Hi!

We're implementing a Repast simulation for a university project. For the testing part we are also using JUnit, I've browsed github to find some examples how to incorporate JUnit with Repast.

I've stumbed across your code here:
Oekoflex/src-test/hsoines/oekoflex/tools/RepastTestSample.java

`
assertEquals(0, RunEnvironment.getInstance().getCurrentSchedule().getTickCount(), 0.001);
for (int i = 0; i < 5; ++i) {
schedule.execute();    // geht nicht.
}
assertEquals(4, RunEnvironment.getInstance().getCurrentSchedule().getTickCount(), 0.001);
`

It looks like you're worrying why `schedule.execute();` does not increase the tick count to 4.
I've wondered that myself, however, a look at the testing guide (http://repast.sourceforge.net/docs/RepastModelTesting.pdf) reveals, that 

> An important item to note here is that the scheduler
> in Repast Simphony doesn’t just allow for discrete time steps so the fact that the schedule
> is executed 5 times doesn’t necessarily mean that we will find ourselves at tick 5 after the
> for loop, unless there were actions scheduled only to occur on every tick.

While I don't know how your context updates the simulation clock, I believe that events like  
`@ScheduledMethod(start = 1, interval = 1, priority = 5)` seem to be necessary to increase the simulation clock/tick count.

However, I am just in the beginning phase of implementing JUnit with RePast and figuring out myself how to trigger Repast programmatically. So far, my tick count also stays at -1.0 even though I have events at tick 0, resp. 1 that should increase the tick count.

**Comment by Shigawire** [comment]
**Update**

I have no idea how far you got with the scheduled testing, however this is how it got it working:

``` java
for (int i = 0; i < 5; ++i) {
            this.schedule.schedule(customer1);
            this.schedule.execute();
            this.schedule.getTickCount(); //1...5
            System.out.println(this.schedule.toString()); //1...5
        }
```

You must use `schedule.schedule(Object object)`, while object implements @ScheduledMethod like 

``` java
    @ScheduledMethod(start = 1, interval = 1, priority = 5)
    public void run() 
    { ... }

```

Sorry for the ugly code.

**Comment by fr2e** [comment]
Thanks for your hint. Until now I just try not to use too much from Repast when testing. There is also a short introduction from repast about testing with junit called RepastModelTesting.pdf.

**Comment by Shigawire** [comment]
Yes, I've used that initially. Unfortunately, the documentation lacks mentioning `schedule.schedule(Object object)`, that's why I was debugging for hours...
